version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
     commands:
      - echo npm run build
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - touch .env
      - echo -e 'DB_TARGET=local\nDB_CLIENT=mysql\nDB_PORT=3306\nDB_HOST=ls-03a76c10579a258436b330b94f51593549b70422.chqqmkdqkqez.ap-south-1.rds.amazonaws.com\nDB_USER=unisolvedbmaster\nDB_PASSWORD=qSi-a:Nvz,Kf0wo1-I?k!oU[ba_7m<DA\nDB_NAME=unisolve_db\nDB_MIGRATE_FORCE=false\nDB_MIGRATE_ALTER=true' > .env
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/node_modules/**/*'
